In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data = pd.read_csv("CSV파일/suicide_2016.csv")
#data.head()
#data.info(10)

#print(type(data))
data.dropna(how = "all")
data.fillna(0)

C:\Users\GSE\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (117,130,163,174,175) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,CTYPE,M_SUI_TOTAL,MH,E_RES,E_ADVI,E_PARTT,E_ALLWN,GRADE,GROUP,E_SES,...,E_LT_SF,E_LT_M,E_LT_SM,E_EDU_F,E_KRN_F,E_BORN_F,E_EDU_M,E_KRN_M,E_BORN_M,E_S_RCRD
0,대도시,1,중학교,1,5,1,1,1,서울대4-3,1,...,9999,1,9999,3,1,9999,3,1,9999,2
1,대도시,1,중학교,1,1,2,16,1,서울대4-3,5,...,9999,9999,9999,9999,9999,9999,9999,9999,9999,1
2,대도시,1,중학교,1,2,1,3,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,1
3,대도시,1,중학교,1,7,1,2,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,3
4,대도시,1,중학교,1,2,1,8,1,서울대4-3,1,...,9999,1,9999,3,1,9999,3,1,9999,1
5,대도시,1,중학교,1,7,1,2,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,2
6,대도시,1,중학교,1,4,1,2,1,서울대4-3,4,...,9999,1,9999,4,1,9999,4,1,9999,2
7,대도시,-1,중학교,1,2,1,1,1,서울대4-3,2,...,9999,1,9999,4,1,9999,4,1,9999,1
8,대도시,1,중학교,1,2,1,2,1,서울대4-3,1,...,9999,1,9999,3,1,9999,3,1,9999,1
9,대도시,1,중학교,1,4,1,11,1,서울대4-3,1,...,9999,1,9999,3,1,9999,3,1,9999,1
10,대도시,1,중학교,1,7,1,1,1,서울대4-3,3,...,9999,1,9999,4,1,9999,3,1,9999,1
11,대도시,1,중학교,1,2,1,1,1,서울대4-3,1,...,9999,1,9999,3,1,9999,3,1,9999,1
12,대도시,-1,중학교,1,7,1,1,1,서울대4-3,2,...,9999,9999,9999,9999,9999,9999,9999,9999,9999,2
13,대도시,1,중학교,1,2,1,1,1,서울대4-3,1,...,9999,1,9999,3,1,9999,3,1,9999,1
14,대도시,1,중학교,1,2,1,1,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,2
15,대도시,1,중학교,1,1,1,2,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,1
16,대도시,1,중학교,1,2,1,1,1,서울대4-3,1,...,9999,1,9999,3,1,9999,3,1,9999,1
17,대도시,1,중학교,1,2,1,1,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,3
18,대도시,-1,중학교,1,4,1,3,1,서울대4-3,1,...,9999,1,9999,3,1,9999,3,1,9999,1
19,대도시,1,중학교,1,4,1,2,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,2
20,대도시,1,중학교,1,4,1,2,1,서울대4-3,1,...,9999,1,9999,3,1,9999,3,1,9999,2
21,대도시,1,중학교,1,2,1,2,1,서울대4-3,1,...,9999,1,9999,3,1,9999,4,1,9999,2
22,대도시,1,중학교,1,1,1,1,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,1
23,대도시,1,중학교,1,2,1,2,1,서울대4-3,1,...,2,1,2,3,1,9999,3,1,9999,2
24,대도시,1,중학교,1,2,1,2,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,2
25,대도시,1,중학교,1,1,1,1,1,서울대4-3,4,...,9999,1,9999,4,1,9999,4,1,9999,3
26,대도시,1,중학교,1,2,1,6,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,1
27,대도시,1,중학교,1,2,1,2,1,서울대4-3,3,...,9999,1,9999,3,1,9999,3,1,9999,1
28,대도시,1,중학교,1,6,1,2,1,서울대4-3,1,...,9999,1,9999,3,1,9999,3,1,9999,1
29,대도시,1,중학교,1,7,1,2,1,서울대4-3,2,...,9999,1,9999,3,1,9999,3,1,9999,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65498,대도시,1,고등학교,1,5,2,11,5,세종대1-1,5,...,9999,2,9999,2,1,9999,4,1,9999,2
65499,대도시,1,고등학교,1,4,2,3,5,세종대1-1,3,...,9999,1,9999,3,1,9999,2,1,9999,1
65500,대도시,1,고등학교,1,4,1,4,5,세종대1-1,4,...,9999,1,9999,1,1,9999,2,1,9999,1
65501,대도시,1,고등학교,1,7,1,7,5,세종대1-1,3,...,9999,1,9999,4,1,9999,4,1,9999,4
65502,대도시,1,고등학교,1,7,2,2,5,세종대1-1,4,...,9999,2,1,4,1,9999,4,1,9999,2
65503,대도시,1,고등학교,3,7,2,5,5,세종대1-1,4,...,9999,1,9999,3,1,9999,2,1,9999,4
65504,대도시,1,고등학교,1,7,1,1,5,세종대1-1,4,...,9999,1,9999,2,1,9999,2,1,9999,2
65505,대도시,1,고등학교,1,7,2,3,5,세종대1-1,5,...,9999,9999,9999,1,1,9999,9999,9999,9999,1
65506,대도시,1,고등학교,1,7,1,3,5,세종대1-1,3,...,9999,1,9999,2,1,9999,2,1,9999,4
65507,대도시,1,고등학교,3,1,1,2,5,세종대1-1,2,...,9999,1,9999,4,1,9999,4,1,9999,3
65508,대도시,1,고등학교,1,4,1,1,5,세종대1-1,4,...,9999,9999,9999,1,1,9999,9999,9999,9999,1
65509,대도시,1,고등학교,1,7,1,1,6,세종대1-1,3,...,9999,1,9999,2,1,9999,2,1,9999,2
65510,대도시,1,고등학교,1,1,1,1,6,세종대1-1,5,...,9999,1,9999,2,1,9999,1,1,9999,3
65511,대도시,1,고등학교,1,7,2,2,6,세종대1-1,4,...,9999,1,9999,2,1,9999,2,2,2,1
65512,대도시,1,고등학교,1,4,2,7,6,세종대1-1,2,...,9999,2,1,1,1,9999,4,1,9999,3
65513,대도시,1,고등학교,1,6,2,11,6,세종대1-1,2,...,9999,9999,9999,9999,9999,9999,9999,9999,9999,2
65514,대도시,1,고등학교,1,6,2,3,6,세종대1-1,4,...,2,2,2,1,1,9999,2,1,9999,2
65515,대도시,1,고등학교,2,4,2,15,6,세종대1-1,4,...,9999,1,9999,2,1,9999,2,1,9999,2
65516,대도시,1,고등학교,1,7,2,2,6,세종대1-1,3,...,9999,1,9999,4,1,9999,4,2,5,4
65517,대도시,1,고등학교,1,4,1,16,6,세종대1-1,3,...,9999,1,9999,3,1,9999,3,1,9999,3
65518,대도시,1,고등학교,1,4,1,7,6,세종대1-1,3,...,9999,1,9999,2,1,9999,3,1,9999,3
65519,대도시,1,고등학교,1,7,1,2,6,세종대1-1,3,...,9999,1,9999,3,1,9999,2,1,9999,2
65520,대도시,1,고등학교,1,7,1,4,6,세종대1-1,3,...,9999,1,9999,2,1,9999,2,1,9999,3
65521,대도시,1,고등학교,1,4,2,2,6,세종대1-1,3,...,9999,1,9999,2,1,9999,2,1,9999,2
65522,대도시,1,고등학교,1,1,1,1,6,세종대1-1,3,...,9999,1,9999,2,1,9999,2,1,9999,2
65523,대도시,1,고등학교,1,2,2,2,6,세종대1-1,5,...,9999,1,9999,2,1,9999,2,1,9999,4
65524,대도시,1,고등학교,1,4,1,8,6,세종대1-1,3,...,9999,1,9999,2,1,9999,2,1,9999,2
65525,대도시,1,고등학교,1,7,2,2,6,세종대1-1,3,...,9999,1,9999,3,1,9999,3,1,9999,3
65526,대도시,1,고등학교,1,4,2,2,6,세종대1-1,4,...,9999,1,9999,2,1,9999,2,1,9999,2
65527,대도시,1,고등학교,1,4,2,4,6,세종대1-1,3,...,9999,2,9999,2,1,9999,2,1,9999,2

In [39]:
data['INT_WD_MM'][4]

' '

In [20]:
val_data = pd.read_csv("CSV파일/2016자살변수정보.csv")
val_data.head()
#s = "YEAR"

       us w  문자  24  0        변수이름  지정않음 지정않음.1  8   왼쪽     명목형  입력
0     mod_d  문자  36  0   최종 DB 수정일  지정않음   지정않음  8   왼쪽     명목형  입력
1      YEAR  숫자   4  0        조사연도  지정않음   지정않음  8  오른쪽  알 수 없음  입력
2      CITY  문자  12  0          시도  지정않음   지정않음  8   왼쪽     명목형  입력
3     CTYPE  문자  24  0        도시규모  지정않음   지정않음  8   왼쪽     명목형  입력
4  CTYPE_SD  문자  24  0  도시규모(표본설계)  지정않음   지정않음  8   왼쪽     명목형  입력

In [33]:
data =data.drop(["CTYPE"], axis=1)
data = data.drop(["MH"], axis=1)
data = data.drop(["GROUP"], axis=1)
data = data.drop(["HT"], axis=1)
data = data.drop(["WT"], axis=1)
data = data.drop(["M_SUI_CON"], axis=1)
data = data.drop(["M_SUI_PLN"], axis=1)
data = data.drop(["M_SUI_ATT"], axis=1)
#data = data.drop(['INT_WD_MM'], axis =1) # 일단 제거

In [34]:
list = []
for i in range(len(data.columns)):
    val = data.columns[i]    
    if data[val].dtype == object:
        list.append(val)

        
print(list)

['F_DRINK_K', 'PA_WLK_MM', 'PA_SWD_S', 'PA_SWD_N', 'PA_SWK_S', 'PA_SWK_N', 'M_SLP_HR', 'M_SLP_MM', 'M_WK_HR', 'M_WK_MM', 'AC_FAGE', 'TC_FAGE', 'TC_DAGE', 'TC_EC_FAGE', 'S_FAGE', 'S_PREG', 'S_ABOR', 'INT_WD_MM1', 'INT_WD_MM2', 'INT_WK_MM1', 'INT_WK_MM2', 'AGE', 'AGE_M']

In [35]:
data = data.replace(['1',1,' ','9999',9999], [1,1,0,0,0])

In [36]:
list = []
for i in range(len(data.columns)):
    val = data.columns[i]    
    if data[val].dtype == object:
        list.append(val)

        
print(list)

[]

In [57]:
corr_matrix = data.corr()
corr_matrix["M_SUI_TOTAL"].sort_values(ascending=False)

M_SUI_TOTAL    1.000000
AC_SND_2       0.098122
AC_SND_4       0.079950
M_SLP_HR       0.066594
M_SLP_HR_K     0.058131
AC_ALLOW       0.057065
AC_SND_3       0.056492
F_BR           0.053564
TC_CSN         0.051539
AC_SND_1       0.050886
E_FM_M_3       0.043312
E_FM_F_1       0.038376
PA_VIG         0.037838
PA_PE_FQ       0.037118
M_WK_HR        0.036227
E_KRN_F        0.033838
E_EDU_F        0.033131
TC_TAD_NO_5    0.028512
AGE_M          0.028181
F_FRUIT        0.027844
AGE            0.027483
PA_MSC         0.025180
TC_AD_TV_2     0.022082
PA_TOT         0.021518
F_EDU          0.020743
E_FM_OBS_7     0.014910
MH             0.014627
I_SCH_ED2      0.011901
E_FM_GF_5      0.009747
NO1            0.008445
                 ...
TC_LT         -0.071484
TC_AMNT       -0.072228
S_SI          -0.072662
Unnamed: 11   -0.074134
S_SI_AC       -0.074748
TC_SND_S      -0.075050
AC_PLC_1      -0.076478
E_SES         -0.076720
S_PREG        -0.077832
DR_EXP        -0.079869
I_EAR_TRT     -0.080682
DR_LT         -0.081968
AC_ACCESS     -0.084222
AC_AMNT       -0.086205
O_SYMP2       -0.086324
TC_SND_H      -0.090107
AC_LT         -0.091331
O_SYMP4       -0.093049
I_SCH         -0.097583
O_SYMP3       -0.104467
AC_DRUNK      -0.110687
AC_DAYS       -0.114756
SEX           -0.118583
TC_SND_P      -0.119806
V_TRT         -0.128337
M_SLP_EN      -0.154156
PR_HT         -0.201623
M_STR         -0.289429
M_SAD         -0.446981
E_BORN_M            NaN
Name: M_SUI_TOTAL, Length: 166, dtype: float64

In [37]:

list = []
for i in range(len(data.columns)):
    val = data.columns[i]    
    if data[val].dtype == object:
        list.append(val)

        
print(list)

[]

In [38]:
#object type 확인
count = 0 
for i in range(len(data.columns)):
    val = data.columns[i]    
    if data[val].dtype == object:
        print(val)
        data[val] = data[val].astype(int)
        
        print(data[val].unique())
    elif data[val].dtype == float:
        data[val] = data[val].astype(float)
    else:
        pass

print(count)

0

In [39]:
# null 개수 확인
data.isnull().sum()

M_SUI_TOTAL    0
E_RES          0
E_ADVI         0
E_PARTT        0
E_ALLWN        0
GRADE          0
E_SES          0
FPC            0
PR_HT          0
PR_BI          0
PR_HD          0
PR_OH          0
F_BR           0
F_FRUIT        0
F_DRINK_K      0
F_DRINK_RS     0
F_SODA         0
F_CAFFEINE     0
F_SWDRINK      0
F_FASTFOOD     0
F_VEG          0
F_MILK         0
F_EDU          0
F_FFOOD_K1     0
F_FFOOD_K2     0
F_FFOOD_K3     0
F_FFOOD_K4     0
F_FFOOD_K5     0
F_FFOOD_K6     0
F_FFOOD_K7     0
              ..
ECZ_DG_LT      0
ECZ_DG_YR      0
INT_WD         0
INT_WD_MM1     0
INT_WD_MM2     0
INT_WK         0
INT_WK_MM1     0
INT_WK_MM2     0
AGE            0
AGE_M          0
E_FM_F_1       0
E_FM_SF_2      0
E_FM_M_3       0
E_FM_SM_4      0
E_FM_GF_5      0
E_FM_GM_6      0
E_FM_OBS_7     0
E_FM_YBS_8     0
E_FM_NO_9      0
E_LT_F         0
E_LT_SF        0
E_LT_M         0
E_LT_SM        0
E_EDU_F        0
E_KRN_F        0
E_BORN_F       0
E_EDU_M        0
E_KRN_M        0
E_BORN_M       0
E_S_RCRD       0
Length: 206, dtype: int64

In [43]:
# cancer to DataFrame
import pandas as pd
import numpy as np

# x: data / y : 결과값

x = data.drop(["M_SUI_TOTAL"], axis=1)
y = data["M_SUI_TOTAL"].astype(int)

In [44]:
#Create Test Set
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# 데이터를 test data 20% training data를 80%로 나눈다.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=20)

print(len(x_train))
print(len(x_test))
#print(y_train)
#print(y_test)

52422
13106

In [45]:
# data scaling StandardScaler 사용
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x = sc.fit_transform(x) # x_train data scaling

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import statsmodels.api as sm
from scipy import stats

log_reg = LogisticRegression()
log_reg.fit(x_train,y_train)



x2 = sm.add_constant(x)
y_pred = log_reg.predict(x_test)

model = sm.OLS(y, x)
result = model.fit()
#print(result.summary())# summary함수 하면 로지스틱 회귀분석 결과 나옴

C:\Users\GSE\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [47]:
print(result.summary())
#print(result.summary2().tables[1])# summary함수 하면 로지스틱 회귀분석 결과 나옴

                                 OLS Regression Results
=======================================================================================
Dep. Variable:            M_SUI_TOTAL   R-squared (uncentered):                   0.139
Model:                            OLS   Adj. R-squared (uncentered):              0.136
Method:                 Least Squares   F-statistic:                              51.44
Date:                Sun, 27 Oct 2019   Prob (F-statistic):                        0.00
Time:                        21:55:15   Log-Likelihood:                         -88077.
No. Observations:               65528   AIC:                                  1.766e+05
Df Residuals:                   65323   BIC:                                  1.784e+05
Df Model:                         205
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             0.0021      0.004      0.537      0.591      -0.006       0.010
x2            -0.0208      0.004     -5.422      0.000      -0.028      -0.013
x3             0.0001      0.004      0.032      0.975      -0.008       0.008
x4             0.0054      0.004      1.332      0.183      -0.003       0.013
x5             0.0380      0.008      4.672      0.000       0.022       0.054
x6            -0.0024      0.004     -0.582      0.561      -0.011       0.006
x7            -0.0038      0.005     -0.813      0.416      -0.013       0.005
x8            -0.0028      0.004     -0.656      0.512      -0.011       0.006
x9            -0.0038      0.004     -0.939      0.348      -0.012       0.004
x10           -0.0779      0.005    -16.583      0.000      -0.087      -0.069
x11            0.0093      0.004      2.227      0.026       0.001       0.017
x12           -0.0025      0.004     -0.629      0.529      -0.010       0.005
x13           -0.0058      0.004     -1.439      0.150      -0.014       0.002
x14            0.0010      0.004      0.244      0.807      -0.007       0.009
x15            0.0008      0.004      0.221      0.825      -0.006       0.008
x16            0.0012      0.004      0.273      0.785      -0.008       0.010
x17           -0.0120      0.004     -3.037      0.002      -0.020      -0.004
x18           -0.0012      0.004     -0.284      0.777      -0.009       0.007
x19            0.0035      0.005      0.769      0.442      -0.005       0.012
x20           -0.0042      0.004     -1.066      0.286      -0.012       0.004
x21           -0.0063      0.004     -1.593      0.111      -0.014       0.001
x22            0.0047      0.004      1.103      0.270      -0.004       0.013
x23            0.0023      0.004      0.596      0.551      -0.005       0.010
x24            0.0001      0.004      0.035      0.972      -0.007       0.007
x25           -0.0038      0.004     -0.973      0.331      -0.012       0.004
x26           -0.0012      0.004     -0.309      0.757      -0.009       0.006
x27            0.0042      0.004      1.140      0.254      -0.003       0.011
x28           -0.0005      0.004     -0.130      0.897      -0.008       0.007
x29           -0.0028      0.004     -0.763      0.446      -0.010       0.004
x30            0.0017      0.004      0.443      0.657      -0.006       0.009
x31           -0.0037      0.004     -0.987      0.324      -0.011       0.004
x32           -0.0036      0.004     -0.980      0.327      -0.011       0.004
x33            0.0008      0.004      0.205      0.838      -0.007       0.008
x34           -0.0028      0.004     -0.724      0.469      -0.010       0.005
x35           -0.0014      0.004     -0.379      0.705      -0.009       0.006
x36           -0.0010      0.004     -0.281      0.779      -0.008       0.006
x37           -0.0013      0.004     -0.354      0.723      -0.009       0.006
x38            0.0015      0.004      0.407      0.684      -0.006       0.009
x39            0.0042      0.005      0.880      0.379      -0.005       0.014
x40           -0.0042      0.005     -0.794      0.427      -0.014       0.006
x41            0.0016      0.005      0.350      0.727      -0.007       0.011
x42           -0.0011      0.004     -0.285      0.776      -0.009       0.007
x43            0.0012      0.004      0.311      0.756      -0.006       0.009
x44           -0.0060      0.004     -1.332      0.183      -0.015       0.003
x45            0.0041      0.004      0.973      0.331      -0.004       0.012
x46           -0.0114      0.005     -2.422      0.015      -0.021      -0.002
x47            0.0003      0.004      0.060      0.952      -0.008       0.009
x48            0.0014      0.004      0.340      0.734      -0.007       0.010
x49           -0.0047      0.004     -1.154      0.249      -0.013       0.003
x50           -0.0035      0.004     -0.958      0.338      -0.011       0.004
x51            0.0007      0.005      0.163      0.871      -0.008       0.010
x52        -3.459e-06      0.005     -0.001      0.999      -0.010       0.010
x53           -0.0078      0.004     -1.911      0.056      -0.016       0.000
x54           -0.0029      0.005     -0.592      0.554      -0.012       0.007
x55            0.0047      0.005      0.976      0.329      -0.005       0.014
x56            0.0049      0.005      1.000      0.317      -0.005       0.014
x57           -0.0042      0.005     -0.868      0.385      -0.014       0.005
x58           -0.0121      0.004     -2.692      0.007      -0.021      -0.003
x59            0.0017      0.004      0.406      0.685      -0.006       0.010
x60           -0.0018      0.004     -0.445      0.656      -0.010       0.006
x61           -0.0042      0.004     -0.981      0.327      -0.013       0.004
x62            0.0676      0.005     14.872      0.000       0.059       0.076
x63            0.0006      0.004      0.143      0.887      -0.008       0.009
x64            0.0018      0.005      0.369      0.712      -0.008       0.011
x65           -0.0009      0.004     -0.209      0.834      -0.009       0.007
x66            0.0006      0.004      0.138      0.890      -0.008       0.009
x67            0.0021      0.004      0.541      0.588      -0.005       0.010
x68            0.0040      0.004      0.922      0.357      -0.004       0.012
x69           -0.0006      0.004     -0.154      0.877      -0.008       0.007
x70            0.0017      0.004      0.462      0.644      -0.006       0.009
x71           -0.0014      0.004     -0.357      0.721      -0.009       0.006
x72           -0.1735      0.004    -42.419      0.000      -0.181      -0.165
x73           -0.1899      0.004    -48.977      0.000      -0.198      -0.182
x74           -0.0043      0.004     -1.096      0.273      -0.012       0.003
x75           -0.0022      0.004     -0.515      0.607      -0.011       0.006
x76           -0.0019      0.004     -0.433      0.665      -0.011       0.007
x77           -0.0005      0.005     -0.110      0.913      -0.010       0.009
x78            0.0025      0.005      0.465      0.642      -0.008       0.013
x79           -0.0078      0.004     -1.989      0.047      -0.016      -0.000
x80            0.0067      0.007      0.924      0.356      -0.008       0.021
x81            0.0058      0.004      1.483      0.138      -0.002       0.014
x82           -0.0027      0.004     -0.691      0.490      -0.010       0.005
x83            0.0030      0.005      0.645      0.519      -0.006       0.012
x84            0.0038      0.005      0.822      0.411      -0.005       0.013
x85           -0.0075      0.004     -1.837      0.066      -0.015       0.001
x86           -0.0062      0.004     -1.469      0.142      -0.014       0.002
x87           -0.0057      0.004     -1.420      0.155      -0.013       0.002
x88           -0.0048      0.004     -1.217      0.224      -0.013       0.003
x89           -0.0167      0.004     -4.261      0.000      -0.024      -0.009
x90           -0.0049      0.005     -1.093      0.275      -0.014       0.004
x91            0.0029      0.005      0.625      0.532      -0.006       0.012
x92           -0.0062      0.005     -1.204      0.229      -0.016       0.004
x93           -0.0012      0.005     -0.243      0.808      -0.011       0.009
x94            0.0031      0.005      0.576      0.564      -0.008       0.014
x95           -0.0026      0.005     -0.578      0.563      -0.012       0.006
x96           -0.0024      0.005     -0.517      0.605      -0.012       0.007
x97            0.0057      0.004      1.345      0.179      -0.003       0.014
x98            0.0072      0.004      1.687      0.092      -0.001       0.016
x99            0.0043      0.004      1.045      0.296      -0.004       0.012
x100          -0.0068      0.004     -1.787      0.074      -0.014       0.001
x101          -0.0037      0.006     -0.667      0.505      -0.014       0.007
x102          -0.0033      0.005     -0.719      0.472      -0.012       0.006
x103          -0.0041      0.005     -0.819      0.413      -0.014       0.006
x104          -0.0026      0.004     -0.615      0.538      -0.011       0.006
x105          -0.0038      0.004     -0.935      0.350      -0.012       0.004
x106          -0.0110      0.004     -2.763      0.006      -0.019      -0.003
x107          -0.0119      0.004     -2.754      0.006      -0.020      -0.003
x108          -0.0173      0.011     -1.525      0.127      -0.040       0.005
x109           0.0037      0.010      0.357      0.721      -0.017       0.024
x110           0.0027      0.009      0.304      0.761      -0.015       0.020
x111           0.0064      0.008      0.836      0.403      -0.009       0.021
x112           0.0006      0.006      0.105      0.916      -0.011       0.013
x113          -0.0141      0.005     -3.103      0.002      -0.023      -0.005
x114          -0.0014      0.005     -0.314      0.753      -0.010       0.007
x115           0.0016      0.005      0.357      0.721      -0.007       0.010
x116          -0.0017      0.005     -0.362      0.717      -0.011       0.008
x117          -0.0011      0.005     -0.239      0.811      -0.010       0.008
x118          -0.0086      0.006     -1.457      0.145      -0.020       0.003
x119           0.0060      0.005      1.131      0.258      -0.004       0.016
x120           0.0014      0.004      0.310      0.756      -0.007       0.010
x121          -0.0021      0.016     -0.132      0.895      -0.033       0.029
x122           0.0053      0.013      0.397      0.691      -0.021       0.032
x123          -0.0111      0.006     -1.783      0.075      -0.023       0.001
x124           0.0097      0.018      0.543      0.587      -0.025       0.045
x125          -0.0021      0.008     -0.271      0.786      -0.017       0.013
x126           0.0015      0.012      0.126      0.899      -0.021       0.024
x127          -0.0004      0.011     -0.040      0.968      -0.022       0.021
x128           0.0038      0.010      0.383      0.702      -0.016       0.024
x129           0.0017      0.006      0.280      0.779      -0.010       0.014
x130          -0.0100      0.014     -0.724      0.469      -0.037       0.017
x131          -0.0019      0.006     -0.318      0.751      -0.014       0.010
x132          -0.0039      0.006     -0.680      0.496      -0.015       0.007
x133          -0.0051      0.005     -0.950      0.342      -0.016       0.005
x134          -0.0005      0.004     -0.134      0.894      -0.009       0.007
x135           0.0007      0.004      0.173      0.863      -0.008       0.009
x136           0.0038      0.004      0.852      0.394      -0.005       0.013
x137           0.0026      0.004      0.593      0.553      -0.006       0.011
x138          -0.0054      0.004     -1.239      0.215      -0.014       0.003
x139          -0.0008      0.004     -0.193      0.847      -0.009       0.007
x140          -0.0053      0.005     -1.056      0.291      -0.015       0.005
x141          -0.0093      0.005     -1.804      0.071      -0.019       0.001
x142          -0.0029      0.004     -0.671      0.502      -0.011       0.006
x143          -0.0054      0.006     -0.954      0.340      -0.016       0.006
x144          -0.0066      0.004     -1.609      0.108      -0.015       0.001
x145          -0.0018      0.009     -0.201      0.841      -0.019       0.016
x146           0.0037      0.008      0.445      0.657      -0.012       0.020
x147          -0.0047      0.004     -1.237      0.216      -0.012       0.003
x148          -0.0004      0.004     -0.099      0.922      -0.008       0.008
x149          -0.0034      0.004     -0.820      0.412      -0.011       0.005
x150          -0.0022      0.004     -0.512      0.609      -0.011       0.006
x151        3.954e-05      0.004      0.009      0.993      -0.009       0.009
x152          -0.0118      0.005     -2.420      0.016      -0.021      -0.002
x153           0.0015      0.005      0.334      0.739      -0.007       0.010
x154          -0.0077      0.018     -0.422      0.673      -0.043       0.028
x155           0.0167      0.016      1.063      0.288      -0.014       0.048
x156           0.0025      0.008      0.324      0.746      -0.013       0.018
x157          -0.0079      0.007     -1.097      0.273      -0.022       0.006
x158          -0.0012      0.006     -0.200      0.842      -0.013       0.010
x159          -0.0124      0.005     -2.494      0.013      -0.022      -0.003
x160          -0.0012      0.012     -0.098      0.922      -0.025       0.023
x161          -0.0055      0.005     -1.001      0.317      -0.016       0.005
x162          -0.0073      0.009     -0.839      0.401      -0.024       0.010
x163           0.0202      0.012      1.709      0.088      -0.003       0.043
x164          -0.0088      0.011     -0.823      0.411      -0.030       0.012
x165          -0.0041      0.007     -0.557      0.578      -0.019       0.010
x166          -0.0063      0.005     -1.217      0.224      -0.016       0.004
x167          -0.0012      0.005     -0.256      0.798      -0.010       0.008
x168          -0.0039      0.015     -0.261      0.794      -0.033       0.025
x169           0.0021      0.004      0.490      0.624      -0.006       0.011
x170          -0.0254      0.009     -2.928      0.003      -0.042      -0.008
x171           0.0241      0.009      2.558      0.011       0.006       0.043
x172          -0.0104      0.011     -0.972      0.331      -0.031       0.011
x173           0.0074      0.011      0.694      0.488      -0.014       0.028
x174           0.0064      0.010      0.645      0.519      -0.013       0.026
x175          -0.0041      0.010     -0.417      0.677      -0.024       0.015
x176           0.0024      0.010      0.242      0.809      -0.017       0.022
x177          -0.0063      0.010     -0.644      0.519      -0.026       0.013
x178           0.0021      0.005      0.421      0.674      -0.008       0.012
x179          -0.0012      0.005     -0.242      0.809      -0.011       0.008
x180          -0.0008      0.006     -0.146      0.884      -0.012       0.010
x181           0.0049      0.005      0.929      0.353      -0.005       0.015
x182           0.0015      0.005      0.314      0.753      -0.008       0.011
x183          -0.0148      0.006     -2.428      0.015      -0.027      -0.003
x184          -0.0052      0.026     -0.200      0.841      -0.056       0.045
x185           0.0021      0.027      0.077      0.939      -0.050       0.054
x186          -0.0340      0.024     -1.439      0.150      -0.080       0.012
x187          -0.0234      0.016     -1.440      0.150      -0.055       0.008
x188          -0.0066      0.013     -0.504      0.614      -0.032       0.019
x189          -0.0076      0.017     -0.450      0.653      -0.041       0.026
x190          -0.0053      0.005     -1.038      0.299      -0.015       0.005
x191          -0.0016      0.005     -0.310      0.757      -0.011       0.008
x192           0.0059      0.004      1.339      0.181      -0.003       0.015
x193           0.0006      0.004      0.128      0.898      -0.008       0.009
x194           0.0003      0.004      0.064      0.949      -0.008       0.009
x195           0.0020      0.005      0.404      0.686      -0.008       0.011
x196           0.0244      0.019      1.308      0.191      -0.012       0.061
x197          -0.0030      0.005     -0.554      0.580      -0.014       0.008
x198           0.0061      0.019      0.318      0.751      -0.031       0.043
x199          -0.0029      0.006     -0.500      0.617      -0.014       0.009
x200           0.0383      0.024      1.624      0.104      -0.008       0.084
x201          -0.0034      0.006     -0.557      0.578      -0.015       0.008
x202           0.0032      0.006      0.571      0.568      -0.008       0.014
x203           0.0105      0.013      0.805      0.421      -0.015       0.036
x204          -0.0054      0.006     -0.860      0.390      -0.018       0.007
x205          -0.0064      0.004     -1.556      0.120      -0.014       0.002
==============================================================================
Omnibus:                    21433.707   Durbin-Watson:                   0.709
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            60169.037
Skew:                          -1.764   Prob(JB):                         0.00
Kurtosis:                       6.097   Cond. No.                         39.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [50]:
count = 1
val_count = 0
val_list = []
val_name = []
p_values = result.summary2().tables[1]['P>|t|']
#print(type(p_values.values[2]) <0.05)

for i in range(len(p_values)):
    if round(p_values[i],4) < 0.05:
        print(count , ":",round(p_values[i],4))
        val_count +=1
        val_list.append(count)
    count +=1
print("변수 개수 : ",val_count)
print("변수 위치 : ",val_list)
for i in val_list:
    val_name.append(data.columns[i])


for i in val_name:
    #print(type(i))
    #print(val_data["변수이름"][0])
    for j in range(len(val_data)):
        #print(val_data["OBS"][i],",",val_data["변수이름"][i])
        if val_data["us w"][j] == i:
            print(val_data["변수이름"][j])
print(val_name)

print('정확도 :', metrics.accuracy_score(y_test, y_pred))

2 : 0.0
5 : 0.0
10 : 0.0
11 : 0.0259
17 : 0.0024
46 : 0.0154
58 : 0.0071
62 : 0.0
72 : 0.0
73 : 0.0
79 : 0.0467
89 : 0.0
106 : 0.0057
107 : 0.0059
113 : 0.0019
152 : 0.0155
159 : 0.0126
170 : 0.0034
171 : 0.0105
183 : 0.0152
변수 개수 :  20
변수 위치 :  [2, 5, 10, 11, 17, 46, 58, 62, 72, 73, 79, 89, 106, 107, 113, 152, 159, 170, 171, 183]
고민 상담자
학년
주관적 행복
주관적 구강건강 인지
최근 7일 동안 고카페인 음료 섭취빈도
최근 7일 동안 주말 앉아서 보낸 시간_학습목적
최근 30일 동안 체중조절방법 7)식사 후 구토
평상시 스트레스 인지
최근 12개월 동안 슬픔&절망감 경험
최근 12개월 동안 자살 시도로 병원 치료 경험
현재 사용 구강관리용품 4)전동칫솔
최근 12개월 동안 증상 6)입냄새
이어폰 또는 핸드폰 사용으로 인한 손상 병원치료 경험
최근 12개월 동안 폭력으로 인한 병원 치료 경험
최근 12개월 동안 경험 2)혼자서 음주
친한 친구 현재 흡연
성별
습관적 또는 일부러 약물 경험
평생 약물 경험
주말_학습목적이외_인터넷 이용 총 시간(분)
['E_ADVI', 'GRADE', 'PR_HD', 'PR_OH', 'F_CAFFEINE', 'PA_SWK_S', 'WC_MN_M07', 'M_STR', 'M_SAD', 'M_SUI_TRT', 'O_OCP4', 'O_SYMP6', 'I_EAR_TRT', 'V_TRT', 'AC_CRF2', 'TC_CSBF', 'SEX', 'DR_EXP', 'DR_LT', 'INT_WK_MM2']
정확도 : 0.9047001373416755

In [ ]:
from sklearn import svm
from sklearn.metrics import confusion_matrix

sv = svm.SVC(gamma = 'auto',kernel = 'rbf')
sv.fit(x_train,y_train)
sy_pred = svm.predict(x_test)
print(confusion_matrix(y_test,y_pred))
#print(confusion_matrix(y_test,y_pred))

In [68]:
from sklearn.ensemble import RandomForestClassifier
#
clf = RandomForestClassifier(n_estimators=50,max_depth = 7 ,random_state=2) # 나무의 개수 = 50인 RandomForest
clf.fit(x_train,y_train)
cy_pred = clf.predict(x_test)

In [69]:
# DecisionTree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

dtc = DecisionTreeClassifier(criterion = 'entropy', max_depth = 7) 
#  entropy를 기준으로 사용하고 최대 깊이 7인 DecisionTree.

dtc.fit(x_train,y_train) 
dy_pred = dtc.predict(x_test)
print(confusion_matrix(y_test,dy_pred))

[[  372  1294]
 [  269 10073]]

In [70]:
# 특징 중요도 측정
for name, score in zip(data, dtc.feature_importances_):
    print(name, score)
    if name == "M_SUI_TOTAL":
        pass
    else:
        if score == 0:
            data = data.drop([name], axis=1)

M_SUI_TOTAL 0.0
E_BORN_F 0.0
MH 0.0038966668033792976
CLUSTER 0.0005219104515951202
CTYPE 0.0
E_S_RCRD 0.004085451065716662
E_SES 0.0008353856828974839
E_RES 0.001073302345331194
GRADE 0.0
E_BORN_M 0.0
E_EDU_M 0.0
Unnamed: 11 0.0
E_BORN_M.1 0.001397546359951748
W 0.002884876975425249
FPC 0.02305265224363532
PR_HT 0.0018150119590209087
PR_BI 0.0
F_BR 0.0007961894463227587
F_FRUIT 0.0
F_SODA 0.0
F_SWDRINK 0.0005094347271805293
F_FASTFOOD 0.0
F_EDU 0.0010263602820445202
PA_TOT 0.001705371172770479
PA_VIG 0.0006825384145922848
PA_MSC 0.0
PA_SWD_S 0.0024314746538233144
PA_SWD_N 0.0015578541559702482
PA_SWK_S 0.0015810786979669556
PA_SWK_N 0.002161023759428721
PA_PE_FQ 0.0006016818946878502
WC_MN 0.1415832214840618
M_STR 0.0007747175789357541
M_SLP_EN 0.0
M_SLP_HR 0.0005170437884602947
M_SLP_MM 0.0
M_WK_HR 0.0
M_WK_MM 0.0015893312899362111
M_SLP_HR_K 0.0
M_SLP_MM_K 0.0010099061572712803
M_WK_HR_K 0.0009414907864875124
M_WK_MM_K 0.7028236217394634
M_SAD 0.0011187271539297213
O_BR_FQ 0.0
O_BR_S 0.0
O_SLNT 0.0011479326821798154
O_SYMP1 0.0014898530782874524
O_SYMP1_1 0.0
O_SYMP2 0.0016778194379152033
O_SYMP3 0.0010329269579406515
O_SYMP4 0.0
HW_SPML_S 0.0006645135786579086
HW_SPRM_S 0.0
HW_SPML_H 0.0009700061200852936
HW_SPRM_H 0.0004728043050127917
HW_EDU 0.0010955790287478105
I_SB_FR 0.0
I_SB_BK 0.0
I_SB_EX 0.0014350489125829126
I_HM_MOT 0.0
I_HM_BICY 0.002357651752286491
I_SCH 0.0
I_SCH_TRT 0.0007477100516209588
I_EAR_TRT 0.0
I_SCH_ED1 0.0
I_SCH_ED2 0.0
I_SCH_ED3 0.0
I_SCH_ED4 0.0
I_SCH_ED5 0.022365495148454373
V_TRT 0.001737277840854794
AC_LT 0.0
AC_FAGE 0.0
AC_DAYS 0.0
AC_AMNT 0.0016205296458506912
AC_DRUNK 0.0
AC_PLC_1 0.0
AC_PLC_2 0.0
AC_PLC_3 0.0009757730044779146
AC_PLC_4 0.0
AC_PLC_5 0.0
AC_PLC_6 0.00245157436055459
AC_ACCESS 0.0
AC_EDU 0.0013521670897233442
AC_SND_1 0.0
AC_SND_2 0.00628237725338472
AC_SND_3 0.0
AC_SND_4 0.0
AC_ALLOW 0.0
TC_LT 0.0
TC_FAGE 0.0
TC_DAYS 0.0007159059281831122
TC_DAGE 0.0021242885572614204
TC_AMNT 0.0012905038356071205
TC_PLC 0.0
TC_GET_M 0.0027120250461263842
TC_ACCESS 0.0
TC_QT_YR 0.0
TC_AD_NO_1 0.0
TC_AD_TV_2 0.0
TC_AD_RD_3 0.0
TC_AD_NS_4 0.0013138242315910212
TC_AD_IT_5 0.0
TC_AD_NP_6 0.0
TC_AD_PB_7 0.0
TC_TAD_NO_1 0.0007349875736800818
TC_TAD_NO_2 0.0
TC_TAD_NO_3 0.0
TC_TAD_NO_4 0.0
TC_TAD_NO_5 0.0
TC_SND_H 0.0014619854782379304
TC_SND_S 0.0006928552920338711
TC_SND_P 0.0006928552920338711
TC_EDU 0.0012625916952949227
TC_CSN 0.0
TC_CSF 0.0
TC_CSM 0.0
TC_CSBS 0.0
TC_CSGFM 0.0
TC_CSA 0.0
TC_CSDK 0.0
TC_CSBF 0.0
TC_EC_LT 0.001682962818294954
TC_EC_FAGE 0.0009002058299289925
TC_EC_MN 0.0
TC_HTP_LT 0.0
TC_GHW 0.0017963042582281152
TC_GHW_H 0.0010554912554334322
TC_GHW_QT 0.0033470596370648673
SEX 0.0
S_SI 0.0024507138062297438
S_FAGE 0.0
S_SI_AC 0.0
S_CONT 0.0
S_CONT_M 0.0013340584926315215
S_PREG 0.0
S_EDU 0.0009453407857430592
DR_EXP 0.0
DR_LT 0.0
AS_DG_LT 0.0
AS_DG_YR 0.0
RH_DG_LT 0.000686717362716259
RH_DG_YR 0.0
ECZ_DG_LT 0.0
ECZ_DG_YR 0.0
INT_WD 0.0
INT_WK 0.0034058975907995657
INT_WK_MM 0.0
AGE 0.012454366909810995
AGE_M 0.0
E_FM_F_1 0.0
E_FM_SF_2 0.0
E_FM_M_3 0.0
E_FM_SM_4 0.0
E_FM_GF_5 0.0
E_FM_GM_6 0.0
E_FM_OBS_7 0.0
E_FM_YBS_8 0.0
E_FM_NO_9 0.0
E_LT_F 0.0014019274855457977
E_LT_SF 0.001384642833276567
E_LT_M 0.0
E_LT_SM 0.0005610516347615208
E_EDU_F 0.0
E_KRN_F 0.0007405250505805026
NO1 0.0

In [ ]:
data.info(10)

In [ ]:
corr_matrix = data.corr()
corr_matrix["M_SUI_TOTAL"].sort_values(ascending=False)

In [37]:
# 예측값 측정
#random_forest_pred = clf.predict(x_test) # Random Forest의 test값에 대한 예측 값
Dct_pred = dtc.predict(x_test)# Decision Tree의 test값에 대한 예측 값
#svm_pred = sv.predict(x_test)# SVM의 test값에 대한 예측 값

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=20)

print(len(x_train))
print(len(x_test))

49820
12456

In [ ]:
corr_matrix["M_SUI_CON"]

"""
for i in corr_matrix["M_SUI_CON"]
    if i < 0 :
        data = data.drop[]
        """

In [ ]:
from sklearn import svm
from sklearn.metrics import confusion_matrix

sv = svm.SVC(gamma = 'auto',kernel = 'rbf')
sv.fit(x_train,y_train)
sy_pred = svm.predict(x_test)
print(confusion_matrix(y_test,y_pred))
#print(confusion_matrix(y_test,y_pred))

In [39]:
# F-1 score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

print("Decision Tree accuracy %.2f" %accuracy_score(y_test,Dct_pred))# Decision Tree 값 출력
#print("Random Forest accuracy %.2f" %accuracy_score(y_test,random_forest_pred))# Random Forest 값 출력
#print("SVM accuracy %.2f" %accuracy_score(y_test,svm_pred))# SVM 값 출력

print("Decision f-1 score %.2f" %f1_score(y_test,Dct_pred))# Decision Tree 값 출력
#print("Random f-1 score %.2f" %f1_score(y_test,random_forest_pred))# Random Forest 값 출력
#print("SVM f-1 score %.2f" %f1_score(y_test,svm_pred))# SVM 값 출력

Decision Tree accuracy 0.90
Decision f-1 score 0.95